### ISSUE TITLE
How to Contribute Logos

### ISSUE THREAD

**Issue by InaudibleDirge** [PseudoTV/PseudoTV_Resources#1]
Hey, I'd like to contribute the logos I've made. I'm a little confused on where to add them. Should I upload them to the example folder, or create a new archive?

**Comment by Lunatixz** [comment]
Thanks for the offer; if your collection is part of a "set". For example for a service or matched by color, size, etc... You should create your own resource package by following one of the example packs... packs support compression which I recommend you use. https://kodi.wiki/view/TextureTool

If however your collection is a mix of different logos you've collected; they can be added to the collection below; please try not to remove high quality images for lower quality ones.
https://github.com/PseudoTV/PseudoTV_Logos

Thanks

**Comment by InaudibleDirge** [comment]
Cool. Are you alright with general logos being included in the PseudoTV_Logos folder? (eg: Action Movies) Or should that folder be reserved for real life networks?

**Comment by InaudibleDirge** [comment]
Additionally, it looks like I'm unable to upload. I get "File uploads require push access to this repository." Sorry if this should be obvious. Github contributions are new to me.

**Comment by Lunatixz** [comment]
Yes, You can add custom genre logos (if they are missing).

In Order to contribute, fork the collection and send me a push request.
